library(shiny)
library(shinyFiles)
library(tools)
library(bslib)
library(shinyjs)
library(stringr)
library(processx)
library(readxl)
library(DT)
library(ggplot2)
library(reshape2)
library(ggthemes)
library(umap)
library(factoextra)
library(dplyr)
library(openxlsx)

featureFile = system.file("Docker/PythonScripts","featurespython2.xlsx", package = "RabAnalyser")
featurespython2 <- read_excel(featureFile)
features = c("", colnames(featurespython2))


options(shiny.maxRequestSize=1000*1024^2,
        shiny.launch.browser = .rs.invokeShinyWindowExternal)

cards <- list(
  card(
    h1("Home!!!"),
    h2("Step:  SC_KS_singlePopulation"),
    "This script compares the single cell distributions for each feature with the a
    reference distribution. The reference distribution is generated by aggregating
    all the distribution of single control cells for aech feature. The comparison
    is performed by KS statistic."
  ),
  card(
    h2("Global settings"),
    fluidRow(
      column(4,offset = 1,
             shinyDirButton("folder", "Select Folder in which the results will be saved", "Choose a folder to save results")
      ),
      column(6,
             verbatimTextOutput("folderPath")
      )
    )
  ),
  card(full_screen = T,
       fluidRow(
         column(5,offset = 1,
                fileInput("mat1", "Upload first .mat file (reference distribution)", accept = ".mat")
         ),
         column(5,
                fileInput("mat2", "Upload second .mat file (control distribution)", accept = ".mat")
         )
       ),
       fluidRow(
         column(12,
         selectInput("step2Feature","Select features used for comparing the single cell distributions (if no features are selected, then the comparison will be computed with all of them)",
                     features,width = "100%",
                     selected = "",
                     multiple = TRUE)
         )
       ),
       fluidRow(
         column(5,offset = 1,
                textInput("step2filename",label = "Output file name:", value = "")
         ),
         column(5,
                actionButton("runDocker", "Run Docker")
         )
       )
  ),
  card(
    fluidRow(
      column(6,offset = 1,
             verbatimTextOutput("dockerLine"),
             tags$head(tags$style("#dockerLine{color:red; font-size:12px; font-style:italic; overflow-x:scroll;  overflow-y:scroll; max-height: 100px; background: ghostwhite;}"))
      ),
      column(4,
             verbatimTextOutput("dockerOutput"),
             tags$head(tags$style("#dockerOutput{color:red; font-size:12px; font-style:italic;
overflow-y:scroll; max-height: 250px; background: ghostwhite;}"))
      )
    )
    ),
  card(full_screen = T,
       DT::dataTableOutput("TableStep2", width = "90%")
  ),
  card(
    fluidRow(
      column(10,offset = 1,
             fileInput("singleCNCTN_excel", width = "100%",
                       "Upload execel file generated from SC_KS_singlePopulation step",
                       accept = ".xlsx")
      )
    )
  ),
  card(
    fluidRow(
      column(plotOutput("CorrMatrixBeforeFiltering", height = "300px"), width = 6),
      column(plotOutput("CorrMatrixAfterFiltering", height = "300px"), width = 6)
    )
  ),
  card(
    fluidRow(
      plotOutput("clustChoicePlot", height = "300px"),
        fluidRow(
          column(12,
                 sliderInput("clusterSlider", "Number of Clusters:", min = 0, max = 10, value = 1, step = 1)
          )
        ),
        fluidRow(
          column(10,
                 tableOutput('ClusterIndexesTable')
          ),
          column(2,
                 actionButton("clusterStart", "Cluster!")
          )
        )
    )
  ),
  card(
    fluidRow(
      selectInput("colorUMAPselect", label = "Color the UMAP plot by:", choices = "" )
    ),
    fluidRow(
      plotOutput("coloredUMAPplot", height = "600px")
    )
  )
)


ui <- page_navbar(
  theme =  bs_theme(preset = "united"),
  id = "NavBar",
  title = "RabAnalyser",
  nav_spacer(),
  nav_panel("Home", value = 1,
            fluidRow(cards[[1]]),
            fluidRow(cards[[2]])
            ),
  nav_panel("SC_KS_singlePopulation", value = 2,
            fluidRow(column(6,cards[[3]]),column(6,cards[[4]]) ),
            fluidRow(cards[[5]])
            ),
  nav_panel("SC_singleCNCTN", value = 3,
            fluidRow(cards[[6]]),
            fluidRow(cards[[7]]),
            fluidRow(column(6,cards[[8]]),column(6,cards[[9]]) ) ),
  nav_item(tags$a("Github Link", href = "https://google.it"))
)

# shinyApp(ui, server,
#          options =  options(shiny.maxRequestSize=1000*1024^2,
#                             shiny.launch.browser = .rs.invokeShinyWindowExternal)
# )
