library(shiny)
library(shinyFiles)
library(shinyjs)
library(stringr)
library(readxl)
library(DT)
library(ggplot2)
library(ggthemes)
library(factoextra)
library(dplyr)
library(openxlsx)
library(uwot)
library(reshape2)
library(rstatix)
library(xfun)
library(fs)
library(parallel)
library(shinybusy)
library(randomForest)
library(caret)
library(pheatmap)
library(clusterCrit)
library(bslib)
library(writexl)
# library(leiden)
# library(dbscan)
# library(RANN)

featureFile = system.file("Shiny/files","featurespython2.xlsx", package = "RabAnalyser")
#featureFile = "files/featurespython2.xlsx"

featurespython2 <- read_excel(featureFile)
features = c("", colnames(featurespython2))


# options(shiny.maxRequestSize=1000*1024^2,
#         shiny.launch.browser = .rs.invokeShinyWindowExternal)

cards <- list(
  "home" = card(
    h1("Home!!!"),
    h2("Welcome to the Analysis App"),
    "This app allows you to perform stepwise analysis of single-cell distributions."
  ),
  "HomeStep_singlePopulation" = card(
    h2("Step: SC_KS_singlePopulation"),
    "This script compares single-cell distributions for each feature with a reference distribution.",
    "The reference distribution is generated by aggregating all control cell distributions for each feature.",
    "The comparison is performed using the Kolmogorov-Smirnov (KS) statistic."
  ),
  "HomeStep_Clustering" = card(
    h2("Step: Clustering"),
    "This script analyse the data matrices obtained by the
    'SC_KS_singlePopulation' script to perform subpopulation
    identification and characterization. If one file is loaded, the single
    condition is considered singularly. While if multple files are loaded,
    then it is possible to select a control that will be merged in an unique data matrix
    with the other file (that are defined as treatments) to allow direct comparison among the conditions."
  ),
  "GlobSetting" = card(
    h2("Global settings"),
    fluidRow(
      column(4,offset = 1,
             shinyDirButton("folder", "Select Folder in which the results will be saved", "Choose a folder to save results")
      ),
      column(6,
             verbatimTextOutput("folderPath")
      )
    )
  ),
  "singlePopulation_Load" = card(full_screen = T,
                                 fluidRow(
                                   column(5,offset = 1,
                                          fileInput("mat1", "Upload first .mat file (reference distribution)", accept = ".mat")
                                   ),
                                   column(5,
                                          fileInput("mat2", "Upload second .mat file (control distribution)", accept = ".mat")
                                   )
                                 ),
                                 fluidRow(
                                   column(12,
                                          selectInput("step2Feature","Select features used for comparing the single cell distributions (if no features are selected, then the comparison will be computed with all of them)",
                                                      features,width = "100%",
                                                      selected = "",
                                                      multiple = TRUE)
                                   )
                                 ),
                                 fluidRow(
                                   column(5,offset = 1,
                                          textInput("step2filename",label = "Output file name:", value = "")
                                   ),
                                   column(5,
                                          actionButton("runStep2", "Run")
                                   )
                                 )
  ),
  "singlePopulation_Docker" = card(
    fluidRow(
      column(6,offset = 1,
             verbatimTextOutput("dockerLine"),
             tags$head(tags$style("#dockerLine{color:red; font-size:12px; font-style:italic; overflow-x:scroll;  overflow-y:scroll; max-height: 100px; background: ghostwhite;}"))
      ),
      column(4,
             verbatimTextOutput("dockerOutput"),
             tags$head(tags$style("#dockerOutput{color:red; font-size:12px; font-style:italic;
overflow-y:scroll; max-height: 250px; background: ghostwhite;}"))
      )
    )
  ),
  "singlePopulation_Table" = card(full_screen = T,
                                  DT::dataTableOutput("TableStep2", width = "90%")
  ),
  "Clustering_Load" = card(
    fluidRow(
      column(10,offset = 1,
             fileInput("Clustering_excel", width = "100%",
                       "Upload execel files generated from SC_KS_singlePopulation step",
                       multiple = T,
                       accept = ".xlsx")
      )
    )
  ),
  "Clustering_CorrMat" = card(
    fluidRow(
      column(plotOutput("CorrMatrixBeforeFiltering", height = "300px"), width = 6),
      column(plotOutput("CorrMatrixAfterFiltering", height = "300px"), width = 6)
    )
  ),
  "Clustering_Cluster" = card(
    fluidRow(
      fluidRow(
        column(8,
               plotOutput("Clustering_clustChoicePlot", height = "300px"),
        ),
        column(4,
               tableOutput('Clustering_ClusterIndexesTable')
        )
      ),
      fluidRow(
        column(6,
               sliderInput("Clustering_clusterSlider", "Number of Clusters:", min = 2, max = 10, value = 2, step = 1)
        ),
        column(offset = 4, width = 2,
               actionButton("Clustering_clusterStart", "Cluster!")
        )
      )
    )
  ),
  "Clustering_UMAP" = card(
    fluidRow(
      column(6,
             selectInput("Clustering_colorUMAPselect", label = "Color the UMAP plot by:", choices = "" )
      ),
      column(2,offset = 3,
             actionButton("EDIT_Clustering_colorUMAP",label = "Edit/Save" )
      )
    ),
    fluidRow(
      column(12,
             plotOutput("Clustering_coloredUMAPplot"),
             plotOutput("Clustering_ProportionPlot")
      )
    )
  ),
  "Clustering_clustviolin" = card(
    fluidRow(
      column(6,
             selectInput("Clustering_ViolinColor", label = "Color the violin plot by:", choices = "" )
      ),
      column(2,offset = 3,
             actionButton("EDIT_Clustering_violin",label = "Edit/Save" )
      ),
      uiOutput("UI_clustviolin")
    ),
    fluidRow(
      column(12,
             plotOutput("Clustering_ClusterViolinplot"),
             uiOutput("UI_statTables")
      )
    )
  ),
  "Clustering_FoldChangePval" = card(
    fluidRow(
      column(12, plotOutput("Clustering_FoldChangePlot", height = "600px"))
    )
  ),
  "Clustering_featureSelection" = card(
    fluidRow(
      column(12,plotOutput("Clustering_FeaturePlot", height = "600px"))
    )
  ),
  "Clustering_SubPop" = card(
    uiOutput("UI_clustsubpop"),
    fluidRow(
      column(12,plotOutput("Clustering_SubPopPlot", height = "600px"))
    )
  )
)


ui <- page_navbar(
  theme =  bs_theme(preset = "united"),
  id = "NavBar",
  title = "RabAnalyser",
  nav_spacer(),
  nav_panel("Home", value = 1,
            fluidRow(column(width = 12, cards$home) ),
            fluidRow(column(width = 12, cards$GlobSetting) ),
            fluidRow(column(width = 6, cards$HomeStep_singlePopulation),
                     column(width = 6, cards$HomeStep_Clustering))
  ),
  nav_panel("SC_KS_singlePopulation", value = 2,
            fluidRow(column(10,offset = 1,cards$singlePopulation_Load) ),
            fluidRow(column(12,cards$singlePopulation_Table) )
  ),
  nav_panel("SC_Clustering", value = 3,
            fluidRow(column(12,cards$Clustering_Load)),
            fluidRow(column(12,cards$Clustering_CorrMat)),
            fluidRow(column(12,cards$Clustering_Cluster) ),
            fluidRow(column(6,cards$Clustering_UMAP),column(6,cards$Clustering_clustviolin) ),
            fluidRow(column(6,cards$Clustering_FoldChangePval), column(6,cards$Clustering_featureSelection) ),
            fluidRow(column(12,cards$Clustering_SubPop))
  ),
  nav_item(tags$a("Github Link", href = "https://google.it"))
)

# shinyApp(ui, server,
#          options =  options(shiny.maxRequestSize=1000*1024^2,
#                             shiny.launch.browser = .rs.invokeShinyWindowExternal)
# )
