library(shiny)
library(shinyFiles)
library(tools)
library(bslib)
library(shinyjs)
library(stringr)
library(processx)
library(readxl)
library(DT)
library(ggplot2)
library(reshape2)
library(ggthemes)
library(umap)
library(factoextra)
library(dplyr)
library(openxlsx)
library(rstatix)
library(xfun)
library(fs)
library(parallel)
library(shinybusy)
library(randomForest)
library(caret)
library(pheatmap)

featureFile = system.file("Docker/PythonScripts","featurespython2.xlsx", package = "RabAnalyser")
featurespython2 <- read_excel(featureFile)
features = c("", colnames(featurespython2))


options(shiny.maxRequestSize=1000*1024^2,
        shiny.launch.browser = .rs.invokeShinyWindowExternal)

cards <- list(
  "home" = card(
    h1("Home!!!"),
    h2("Welcome to the Analysis App"),
    "This app allows you to perform stepwise analysis of single-cell distributions."
  ),
  "HomeStep_singlePopulation" = card(
    h2("Step: SC_KS_singlePopulation"),
    "This script compares single-cell distributions for each feature with a reference distribution.",
    "The reference distribution is generated by aggregating all control cell distributions for each feature.",
    "The comparison is performed using the Kolmogorov-Smirnov (KS) statistic."
  ),
  "HomeStep_singleCNDTN" = card(
    h2("Step:  SC_KS_singleCNDTN"),
    "This script analyse the data matrix obtained by the
    'SC_KS_singlePopulation' script to perform subpopulation
    identification and characterization. Here, each single
    condition is considered singularly."
  ),
  "GlobSetting" = card(
    h2("Global settings"),
    fluidRow(
      column(4,offset = 1,
             shinyDirButton("folder", "Select Folder in which the results will be saved", "Choose a folder to save results")
      ),
      column(6,
             verbatimTextOutput("folderPath")
      )
    )
  ),
  "singlePopulation_Load" = card(full_screen = T,
                                 fluidRow(
                                   column(5,offset = 1,
                                          fileInput("mat1", "Upload first .mat file (reference distribution)", accept = ".mat")
                                   ),
                                   column(5,
                                          fileInput("mat2", "Upload second .mat file (control distribution)", accept = ".mat")
                                   )
                                 ),
                                 fluidRow(
                                   column(12,
                                          selectInput("step2Feature","Select features used for comparing the single cell distributions (if no features are selected, then the comparison will be computed with all of them)",
                                                      features,width = "100%",
                                                      selected = "",
                                                      multiple = TRUE)
                                   )
                                 ),
                                 fluidRow(
                                   column(5,offset = 1,
                                          textInput("step2filename",label = "Output file name:", value = "")
                                   ),
                                   column(5,
                                          actionButton("runStep2", "Run")
                                   )
                                 )
  ),
  "singlePopulation_Docker" = card(
    fluidRow(
      column(6,offset = 1,
             verbatimTextOutput("dockerLine"),
             tags$head(tags$style("#dockerLine{color:red; font-size:12px; font-style:italic; overflow-x:scroll;  overflow-y:scroll; max-height: 100px; background: ghostwhite;}"))
      ),
      column(4,
             verbatimTextOutput("dockerOutput"),
             tags$head(tags$style("#dockerOutput{color:red; font-size:12px; font-style:italic;
overflow-y:scroll; max-height: 250px; background: ghostwhite;}"))
      )
    )
  ),
  "singlePopulation_Table" = card(full_screen = T,
                                  DT::dataTableOutput("TableStep2", width = "90%")
  ),
  "singleCNCTN_Load" = card(
    fluidRow(
      column(10,offset = 1,
             fileInput("singleCNCTN_excel", width = "100%",
                       "Upload execel file generated from SC_KS_singlePopulation step",
                       accept = ".xlsx")
      )
    )
  ),
  "singleCNCTN_CorrMat" = card(
    fluidRow(
      column(plotOutput("CorrMatrixBeforeFiltering", height = "300px"), width = 6),
      column(plotOutput("CorrMatrixAfterFiltering", height = "300px"), width = 6)
    )
  ),
  "singleCNCTN_Cluster" = card(
    fluidRow(
      plotOutput("singleCNCTN_clustChoicePlot", height = "300px"),
      fluidRow(
        column(12,
               sliderInput("singleCNCTN_clusterSlider", "Number of Clusters:", min = 0, max = 10, value = 1, step = 1)
        )
      ),
      fluidRow(
        column(10,
               tableOutput('singleCNCTN_ClusterIndexesTable')
        ),
        column(2,
               actionButton("singleCNCTN_clusterStart", "Cluster!")
        )
      )
    )
  ),
  "singleCNCTN_UMAP" = card(
    fluidRow(
      column(4,
        selectInput("singleCNCTN_colorUMAPselect", label = "Color the UMAP plot by:", choices = "" )
      ),
      column(2,offset = 6,
        actionButton("EDIT_singleCNCTN_colorUMAP",label = "Edit/Save" )
      )
    ),
    fluidRow(
      plotOutput("singleCNCTN_coloredUMAPplot", height = "600px")
    )
  ),
  "singleCNCTN_clustviolin" = card(
    fluidRow(
      column(4,
             selectInput("singleCNCTN_ViolinColor", label = "Color the violin plot by:", choices = "" )
             ),
      column(2,offset = 6,
             actionButton("EDIT_singleCNCTN_violin",label = "Edit/Save" )
             )
    ),
    fluidRow(
      plotOutput("singleCNCTN_ClusterViolinplot", height = "600px"),
      tableOutput("singleCNCTN_Stattest")
    )
  ),
  "singleCNCTN_featureSelection" = card(
    fluidRow(
      plotOutput("singleCNCTN_FeaturePlot", height = "600px")
    )
  ),
  "singleCNCTN_SubPop" = card(
    fluidRow(
      plotOutput("singleCNCTN_SubPopPlot", height = "600px")
    )
  )
)


ui <- page_navbar(
  theme =  bs_theme(preset = "united"),
  id = "NavBar",
  title = "RabAnalyser",
  nav_spacer(),
  nav_panel("Home", value = 1,
            fluidRow(column(width = 12, cards$home) ),
            fluidRow(column(width = 12, cards$GlobSetting) ),
            fluidRow(column(width = 6, cards$HomeStep_singlePopulation),
                     column(width = 6, cards$HomeStep_singleCNDTN))
  ),
  nav_panel("SC_KS_singlePopulation", value = 2,
            fluidRow(column(10,offset = 1,cards$singlePopulation_Load) ),
            fluidRow(column(12,cards$singlePopulation_Table) )
  ),
  nav_panel("SC_singleCNCTN", value = 3,
            fluidRow(column(12,cards$singleCNCTN_Load)),
            fluidRow(column(12,cards$singleCNCTN_CorrMat)),
            fluidRow(column(6,cards$singleCNCTN_Cluster,cards$singleCNCTN_clustviolin),
                     column(6,cards$singleCNCTN_UMAP, cards$singleCNCTN_featureSelection)),
            fluidRow(column(12,cards$singleCNCTN_SubPop))
  ),
  nav_item(tags$a("Github Link", href = "https://google.it"))
)

# shinyApp(ui, server,
#          options =  options(shiny.maxRequestSize=1000*1024^2,
#                             shiny.launch.browser = .rs.invokeShinyWindowExternal)
# )
